Apply rules test
systemaccounting/mxfactorial pull request #103
Opened 2019-06-09 07:36 UTC by ryancheta

My first PR. Don't haze the n00b please. 👍🏾

2019-06-09 18:47 UTC, mxfactorial requested changes

2019-06-09 18:47 UTC, mxfactorial commented on services/rules-faas/tests/applyRules.test.js
> +    // {
remove unused items

2019-06-09 18:47 UTC, mxfactorial commented on services/rules-faas/tests/applyRules.test.js
> +        console.log(with_sales_tax)
remove logging

2019-06-09 18:47 UTC, mxfactorial commented on services/rules-faas/tests/applyRules.test.js
> +            expect(items[i].author ).toEqual(transaction_items[i].author);
use [asi](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Automatic_semicolon_insertion); remove semicolon

also, remove space after expect argument.

2019-06-09 18:47 UTC, mxfactorial commented on services/rules-faas/tests/applyRules.test.js
> +const with_sales_tax = applyRules( uuidv1(), transaction_items )
spaces **between** arguments only.
remove space before initial argument and after last argument

2019-06-09 18:59 UTC, mxfactorial requested changes

2019-06-09 18:59 UTC, mxfactorial commented on services/rules-faas/tests/applyRules.test.js
> +        let isOK = false
not used; removed

2019-06-10 08:30 UTC, oozywaters commented on services/rules-faas/tests/applyRules.test.js
> +    name: 'Paper Towels',
Add indentation please

2019-06-10 08:34 UTC, oozywaters commented on services/rules-faas/tests/applyRules.test.js
> +                expect( item.price ).toEqual( parseFloat(item.price).toFixed(3) )
redundant spaces around function arguments

2019-06-10 08:37 UTC, oozywaters commented
Please, set up eslint in your IDE to avoid code styling issues

2019-06-16 05:08 UTC, merged