Terraform api-gateway module
systemaccounting/mxfactorial pull request #81
Opened 2018-12-25 19:13 UTC by oozywaters

2018-12-25 19:17 UTC, oozywaters commented
Ready for review

2018-12-26 02:23 UTC, mxfactorial requested changes
see notes

2018-12-26 02:23 UTC, mxfactorial commented on terraform/modules/api-gateway/main.tf
> +resource "aws_iam_role" "cloudwatch" {
```suggestion
 resource "aws_iam_role" "api_gateway_cloudwatch" {
```

2018-12-26 02:23 UTC, mxfactorial commented on terraform/modules/api-gateway/main.tf
> +resource "aws_iam_role" "cloudwatch" {
conflicts avoided by specific identifiers

2018-12-26 02:23 UTC, mxfactorial commented on terraform/modules/api-gateway/main.tf
> +resource "aws_iam_role_policy" "cloudwatch" {
```suggestion
 resource "aws_iam_role_policy" "api_gateway_cloudwatch" {
```

2018-12-26 02:23 UTC, mxfactorial commented on terraform/modules/api-gateway/main.tf
> +  role = "${aws_iam_role.cloudwatch.id}"
```suggestion
   role = "${aws_iam_role.api_gateway_cloudwatch.id}"
```

2018-12-26 02:23 UTC, mxfactorial commented on terraform/modules/api-gateway/main.tf
> +  cloudwatch_role_arn = "${aws_iam_role.cloudwatch.arn}"
```suggestion
   cloudwatch_role_arn = "${aws_iam_role.api_gateway_cloudwatch.arn}"
```

2018-12-26 02:34 UTC, mxfactorial commented on terraform/workspaces/api-gateway.tf
> +  source = "../modules/api-gateway"
:clap: :clap: :clap: :clap:

2018-12-26 02:50 UTC, mxfactorial commented
specifically, error returned after applying in prod:
```
Error: Error applying plan:

1 error(s) occurred:

* module.api_gateway.aws_iam_role.cloudwatch: 1 error(s) occurred:

* aws_iam_role.cloudwatch: Error creating IAM Role mxfactorial-cloudwatch-role-prod: EntityAlreadyExists: Role with name mxfactorial-cloudwatch-role-prod already exists.
	status code: 409, request id: 57994dbb-08b8-11e9-a5fd-6defa18ece07
```

2018-12-26 18:46 UTC, mxfactorial approved these changes

2018-12-26 18:47 UTC, merged